backend/build_migration/todo/urls.py
from django.conf import settings
from django.urls import path

from build_migration.todo import views
from build_migration.todo.features import HAS_TASK_MERGE

app_name = "todo"

urlpatterns = [
    path("", views.list_lists, name="lists"),
    # View reorder_tasks is only called by JQuery for drag/drop task ordering.
    path("reorder_tasks/", views.reorder_tasks, name="reorder_tasks"),
    # Allow users to post tasks from outside django-todo (e.g. for filing tickets - see docs)
    path("ticket/add/", views.external_add, name="external_add"),
    # Three paths into `list_detail` view
    path("mine/", views.list_detail, {"list_slug": "mine"}, name="mine"),
    path(
        "<int:list_id>/<str:list_slug>/completed/",
        views.list_detail,
        {"view_completed": True},
        name="list_detail_completed",
    ),
    path("<int:list_id>/<str:list_slug>/", views.list_detail, name="list_detail"),
    path("<int:list_id>/<str:list_slug>/delete/", views.del_list, name="del_list"),
    path("add_list/", views.add_list, name="add_list"),
    path("task/<int:task_id>/", views.task_detail, name="task_detail"),
    path(
        "attachment/remove/<int:attachment_id>/", views.remove_attachment, name="remove_attachment"
    ),
]

if HAS_TASK_MERGE:
    # ensure mail tracker autocomplete is optional
    from build_migration.todo.views.task_autocomplete import TaskAutocomplete

    urlpatterns.append(
        path(
            "task/<int:task_id>/autocomplete/", TaskAutocomplete.as_view(), name="task_autocomplete"
        )
    )

urlpatterns.extend(
    [
        path("toggle_done/<int:task_id>/", views.toggle_done, name="task_toggle_done"),
        path("delete/<int:task_id>/", views.delete_task, name="delete_task"),
        path("search/", views.search, name="search"),
        path("import_csv/", views.import_csv, name="import_csv"),
    ]
)

backend/config/urls.py
import os

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import authentication, permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Build migration API",
        default_version="v1",
        description="API documentation for Build migration",
    ),
    validators=["flex", "ssv"],
    public=False,
    permission_classes=(permissions.IsAdminUser,),
    authentication_classes=(
        authentication.TokenAuthentication,
        authentication.SessionAuthentication,
    ),
)

urlpatterns = [
    url(r"^lists/", include("build_migration.todo.urls")),
    url(r"^healthz/", include("health_check.urls")),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # User management
    url(r"^users/", include("build_migration.users.urls")),
    url(r"^rest-auth/", include("rest_auth.urls")),
    url(r"^api-auth/", include("rest_framework.urls")),
    url(
        r"^docs/$",
        schema_view.with_ui("redoc", cache_timeout=None),
        name="schema-redoc",
    ),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

if os.environ.get("DJANGO_SETTINGS_MODULE") == "config.settings.production":
    urlpatterns += [url(r"^prometheus/", include("django_prometheus.urls"))]

backend/build_migration/todo/models.py
from __future__ import unicode_literals

import datetime
import os
import textwrap

from django.conf import settings
from django.contrib.auth.models import Group
from django.db import DEFAULT_DB_ALIAS, models
from django.db.transaction import Atomic, get_connection
from django.urls import reverse
from django.utils import timezone

from django_deprecation import DeprecatedField


def get_attachment_upload_dir(instance, filename):
    """Determine upload dir for task attachment files.
    """

    return "/".join(["tasks", "attachments", str(instance.task.id), filename])


class LockedAtomicTransaction(Atomic):
    """
    modified from https://stackoverflow.com/a/41831049
    this is needed for safely merging

    Does a atomic transaction, but also locks the entire table for any transactions, for the duration of this
    transaction. Although this is the only way to avoid concurrency issues in certain situations, it should be used with
    caution, since it has impacts on performance, for obvious reasons...
    """

    def __init__(self, *models, using=None, savepoint=None):
        if using is None:
            using = DEFAULT_DB_ALIAS
        super().__init__(using, savepoint)
        self.models = models

    def __enter__(self):
        super(LockedAtomicTransaction, self).__enter__()

        # Make sure not to lock, when sqlite is used, or you'll run into problems while running tests!!!
        if settings.DATABASES[self.using]["ENGINE"] != "django.db.backends.sqlite3":
            cursor = None
            try:
                cursor = get_connection(self.using).cursor()
                for model in self.models:
                    cursor.execute(
                        "LOCK TABLE {table_name}".format(table_name=model._meta.db_table)
                    )
            finally:
                if cursor and not cursor.closed:
                    cursor.close()


class TaskList(models.Model):
    name = models.CharField(max_length=60)
    slug = models.SlugField(default="")
    group = models.ForeignKey(Group, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Task Lists"

        # Prevents (at the database level) creation of two lists with the same slug in the same group
        unique_together = ("group", "slug")


class Task(models.Model):
    title = models.CharField(max_length=140)
    task_list = models.ForeignKey(TaskList, on_delete=models.CASCADE, null=True)
    created_date = models.DateField(default=timezone.now, blank=True, null=True)
    due_date = models.DateField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    completed_date = models.DateField(blank=True, null=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        related_name="todo_created_by",
        on_delete=models.CASCADE,
    )
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        related_name="todo_assigned_to",
        on_delete=models.CASCADE,
    )
    note = models.TextField(blank=True, null=True)
    priority = models.PositiveIntegerField(blank=True, null=True)

    # Has due date for an instance of this object passed?
    def overdue_status(self):
        "Returns whether the Tasks's due date has passed or not."
        if self.due_date and datetime.date.today() > self.due_date:
            return True

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("todo:task_detail", kwargs={"task_id": self.id})

    # Auto-set the Task creation / completed date
    def save(self, **kwargs):
        # If Task is being marked complete, set the completed_date
        if self.completed:
            self.completed_date = datetime.datetime.now()
        super(Task, self).save()

    def merge_into(self, merge_target):
        if merge_target.pk == self.pk:
            raise ValueError("can't merge a task with self")

        # lock the comments to avoid concurrent additions of comments after the
        # update request. these comments would be irremediably lost because of
        # the cascade clause
        with LockedAtomicTransaction(Comment):
            Comment.objects.filter(task=self).update(task=merge_target)
            self.delete()

    class Meta:
        ordering = ["priority", "created_date"]


class Comment(models.Model):
    """
    Not using Django's built-in comments because we want to be able to save
    a comment and change task details at the same time. Rolling our own since it's easy.
    """

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True
    )
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.datetime.now)
    email_from = models.CharField(max_length=320, blank=True, null=True)
    email_message_id = models.CharField(max_length=255, blank=True, null=True)

    body = models.TextField(blank=True)

    class Meta:
        # an email should only appear once per task
        unique_together = ("task", "email_message_id")

    @property
    def author_text(self):
        if self.author is not None:
            return str(self.author)

        assert self.email_message_id is not None
        return str(self.email_from)

    @property
    def snippet(self):
        body_snippet = textwrap.shorten(self.body, width=35, placeholder="...")
        # Define here rather than in __str__ so we can use it in the admin list_display
        return "{author} - {snippet}...".format(author=self.author_text, snippet=body_snippet)

    def __str__(self):
        return self.snippet


class Attachment(models.Model):
    """
    Defines a generic file attachment for use in M2M relation with Task.
    """

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=datetime.datetime.now)
    file_object = models.FileField(upload_to=get_attachment_upload_dir, max_length=255)

    def filename(self):
        return os.path.basename(self.file_object.name)

    def extension(self):
        name, extension = os.path.splitext(self.file_object.name)
        return extension

    def __str__(self):
        return f"{self.task.id} - {self.file_object.name}"

backend/build_migration/todo/views/add_list.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.utils.text import slugify

from build_migration.todo.forms import AddTaskListForm
from build_migration.todo.utils import staff_check


@login_required
@user_passes_test(staff_check)
def add_list(request) -> HttpResponse:
    """Allow users to add a new todo list to the group they're in.
    """

    # Only staffers can add lists, regardless of TODO_STAFF_USER setting.
    if not request.user.is_staff:
        raise PermissionDenied

    if request.POST:
        form = AddTaskListForm(request.user, request.POST)
        if form.is_valid():
            try:
                newlist = form.save(commit=False)
                newlist.slug = slugify(newlist.name, allow_unicode=True)
                newlist.save()
                messages.success(request, "A new list has been added.")
                return redirect("todo:lists")

            except IntegrityError:
                messages.warning(
                    request,
                    "There was a problem saving the new list. "
                    "Most likely a list with the same name in the same group already exists.",
                )
    else:
        if request.user.groups.all().count() == 1:
            # FIXME: Assuming first of user's groups here; better to prompt for group
            form = AddTaskListForm(request.user, initial={"group": request.user.groups.all()[0]})
        else:
            form = AddTaskListForm(request.user)

    context = {"form": form}

    return render(request, "todo/add_list.html", context)

backend/build_migration/todo/views/del_list.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from build_migration.todo.models import Task, TaskList
from build_migration.todo.utils import staff_check


@login_required
@user_passes_test(staff_check)
def del_list(request, list_id: int, list_slug: str) -> HttpResponse:
    """Delete an entire list. Only staff members should be allowed to access this view.
    """
    task_list = get_object_or_404(TaskList, id=list_id)

    # Ensure user has permission to delete list. Get the group this list belongs to,
    # and check whether current user is a member of that group AND a staffer.
    if task_list.group not in request.user.groups.all():
        raise PermissionDenied
    if not request.user.is_staff:
        raise PermissionDenied

    if request.method == "POST":
        TaskList.objects.get(id=task_list.id).delete()
        messages.success(request, "{list_name} is gone.".format(list_name=task_list.name))
        return redirect("todo:lists")
    else:
        task_count_done = Task.objects.filter(task_list=task_list.id, completed=True).count()
        task_count_undone = Task.objects.filter(task_list=task_list.id, completed=False).count()
        task_count_total = Task.objects.filter(task_list=task_list.id).count()

    context = {
        "task_list": task_list,
        "task_count_done": task_count_done,
        "task_count_undone": task_count_undone,
        "task_count_total": task_count_total,
    }

    return render(request, "todo/del_list.html", context)

backend/build_migration/todo/views/delete_task.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse

from build_migration.todo.models import Task
from build_migration.todo.utils import staff_check


@login_required
@user_passes_test(staff_check)
def delete_task(request, task_id: int) -> HttpResponse:
    """Delete specified task.
    Redirect to the list from which the task came.
    """

    if request.method == "POST":
        task = get_object_or_404(Task, pk=task_id)

        redir_url = reverse(
            "todo:list_detail",
            kwargs={"list_id": task.task_list.id, "list_slug": task.task_list.slug},
        )

        # Permissions
        if not (
            (task.created_by == request.user)
            or (request.user.is_superuser)
            or (task.assigned_to == request.user)
            or (task.task_list.group in request.user.groups.all())
        ):
            raise PermissionDenied

        task.delete()

        messages.success(request, "Task '{}' has been deleted".format(task.title))
        return redirect(redir_url)

    else:
        raise PermissionDenied

backend/build_migration/todo/views/import_csv.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from django.shortcuts import redirect, render, reverse

from build_migration.todo.operations.csv_importer import CSVImporter
from build_migration.todo.utils import staff_check


@login_required
@user_passes_test(staff_check)
def import_csv(request) -> HttpResponse:
    """Import a specifically formatted CSV into stored tasks.
    """

    ctx = {"results": None}

    if request.method == "POST":
        filepath = request.FILES.get("csvfile")

        if not filepath:
            messages.error(request, "You must supply a CSV file to import.")
            return redirect(reverse("todo:import_csv"))

        importer = CSVImporter()
        results = importer.upsert(filepath)

        if results:
            ctx["results"] = results
        else:
            messages.error(request, "Could not parse provided CSV file.")
            return redirect(reverse("todo:import_csv"))

    return render(request, "todo/import_csv.html", context=ctx)

backend/build_migration/todo/templates/todo/add_list.html
{% extends "todo/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}Add Todo List{% endblock %}
{% block content %}

  <h2>Add a list:</h2>

  <form action="" method="post">
    {% csrf_token %}

    <div class="form-group">
      <label for="id_name">List Name</label>
      <input type="text" class="form-control" id="id_name" name="name" aria-describedby="inputNameHelp" placeholder="">
      <small id="inputNameHelp" class="form-text text-muted">The full display name for this list.</small>
    </div>
    <div class="form-group">
      <label for="id_group">Group</label>
      {{form.group}}
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

backend/build_migration/todo/templates/todo/add_task_external.html
{% extends "todo/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}File Ticket{% endblock %}

{% block content %}

  <h2>{{ task }}</h2>

  <form action="" method="POST">
    {% csrf_token %}

    <h3>File Trouble Ticket</h3>
    <p>
      Have a support issue? Use this form to report the difficulty - we'll get right back to you.
    </p>

    {% if form.errors %}
      {% for error in form.errors %}
        <ul class="errorlist">
          <li>
            <strong>The {{ error|escape }} field is required.</strong>
          </li>
        </ul>
      {% endfor %}
    {% endif %}

    <form action="" name="add_task" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_title" name="title">Subject</label>
          <input type="text" class="form-control" id="id_title" name="title" required placeholder="Our spaceship doesn't go"
            value="{% if form.title.value %}{{ form.title.value }}{% endif %}">
        </div>
        <div class="form-group">
          <label for="id_note">Description</label>
          <textarea class="form-control" id="id_note" name="note" rows="5"
            aria-describedby="inputNoteHelp">{% if form.note.value %}{{ form.note.value }}{% endif %}</textarea>
          <small id="inputNoteHelp" class="form-text text-muted">
            Describe the issue. Please include essential details.
          </small>
        </div>

        <input type="hidden" id="id_priority" name="priority" value="50">
        <p><input type="submit" class="btn btn-primary" name="add_task" value="Submit"></p>
    </form>

{% endblock %}

backend/build_migration/todo/templates/todo/base.html
{% extends "base.html" %}
{% load static %}

{% block extrahead %}
	<!-- CSS and JavaScripts for django-todo -->
	<link rel="stylesheet" type="text/css" href="{% static 'todo/css/styles.css' %}" />
{% endblock extrahead %}

backend/build_migration/todo/templates/todo/list_detail.html
{% extends "todo/base.html" %}
{% load static %}

{% block title %}Todo List: {{ task_list.name }}{% endblock %}

{% block content %}

  {% if list_slug != "mine" %}
    <button class="btn btn-primary" id="AddTaskButton" type="button"
      data-toggle="collapse" data-target="#AddEditTask">Add Task</button>

    {# Task edit / new task form #}
    <div id="AddEditTask" class="collapse">
      {% include 'todo/include/task_edit.html' %}
    </div>
    <hr />
  {% endif %}

  {% if tasks %}
    {% if list_slug == "mine" %}
      <h1>Tasks assigned to me (in all groups)</h1>
    {% else %}
      <h1>{{ view_completed|yesno:"Completed tasks, Tasks" }} in "{{ task_list.name }}"</h1>
      <p><small><i>In workgroup "{{ task_list.group }}" - drag rows to set priorities.</i></small></p>
    {% endif %}

      <table class="table" id="tasktable">
        <tr class="nodrop">
          <th>Task</th>
          <th>Created</th>
          <th>Due on</th>
          <th>Owner</th>
          <th>Assigned</th>
          <th>Mark</th>
        </tr>

        {% for task in tasks %}
          <tr id="{{ task.id }}">
            <td>
                <a href="{% url 'todo:task_detail' task.id %}">{{ task.title|truncatewords:10 }}</a>
            </td>
            <td>
                {{ task.created_date|date:"m/d/Y" }}
            </td>
            <td>
              <span {% if task.overdue_status %}class="overdue"{% endif %}>
                {{ task.due_date|date:"m/d/Y" }}
              </span>
            </td>
            <td>
              {{ task.created_by }}
            </td>
            <td>
              {% if task.assigned_to %}{{ task.assigned_to }}{% else %}Anyone{% endif %}
            </td>
            <td>
              <form method="post" action="{% url "todo:task_toggle_done" task.id %}" role="form">
                {% csrf_token %}
                <button class="btn btn-info btn-sm" type="submit" name="toggle_done">
                  {% if view_completed %}
                    Not Done
                  {% else %}
                    Done
                  {% endif %}
                </button>
              </form>
            </td>
          </tr>
        {% endfor %}
      </table>

      {% include 'todo/include/toggle_delete.html' %}

  {% else %}
    <h4>No tasks on this list yet (add one!)</h4>
    {% include 'todo/include/toggle_delete.html' %}

  {% endif %}

{% endblock %}

{% block extra_js %}
  <script src="{% static 'todo/js/jquery.tablednd_0_5.js' %}" type="text/javascript"></script>

  <script type="text/javascript">
    function order_tasks(data) {
      // The JQuery plugin tableDnD provides a serialize() function which provides the re-ordered
      // data in a list. We pass that list as an object ("data") to a Django view
      // to save new priorities on each task in the list.
      $.post("{% url 'todo:reorder_tasks' %}", data, "json");
      return false;
    };

    $(document).ready(function() {
      // Initialise the task table for drag/drop re-ordering
      $("#tasktable").tableDnD();

      $('#tasktable').tableDnD({
        onDrop: function(table, row) {
          order_tasks($.tableDnD.serialize());
        }
      });

    });

    // When adding a task, change the text of the Add Task button
    function handleClick()
    {
        console.log(this.innerHTML);
        this.innerHTML = (this.innerHTML == 'Add Task' ? 'Cancel' : 'Add Task');
    }
    document.getElementById('AddTaskButton').onclick=handleClick;
  </script>
{% endblock extra_js %}

backend/build_migration/todo/templates/todo/list_lists.html
{% extends "todo/base.html" %}

{% block title %}{{ list_title }} Todo Lists{% endblock %}

{% block content %}
  <h1>Todo Lists</h1>

  <p>{{ task_count }} tasks in {{ list_count }} list{{ list_count|pluralize }}</p>

  {% regroup lists by group as section_list %}
  {% for group in section_list %}
    <h3>Group: {{ group.grouper }}</h3>
    <ul class="list-group mb-4">
      {% for task in group.list %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <a href="{% url 'todo:list_detail' task.id task.slug %}">{{ task.name }}</a>
        <span class="badge badge-primary badge-pill">{{ task.task_set.count }}</span>
      </li>
      {% endfor %}
    </ul>
  {% endfor %}

  <div class="mt-3">
    
    {% if user.is_staff %}
      <a href="{% url 'todo:add_list' %}" class="btn btn-primary">Create new todo list</a>
    {% else %}
      <a href="" class="btn btn-primary disabled">If you were staff, you could create a new list</a>
    {% endif %}
      
  </div>

{% endblock %}

backend/build_migration/todo/templates/todo/task_detail.html
{% extends "todo/base.html" %}

{% block title %}Task:{{ task.title }}{% endblock %}

{% block extrahead %}
<style>
.select2 {
    width: 100% !important;
}

.select2-container {
    min-width: 0 !important;
}
</style>
{{ form.media }}
{{ merge_form.media }}
{% endblock %}



{% block content %}
  <div class="card-deck">
    <div class="card col-sm-8">
      <div class="card-body">
        <h3 class="card-title">{{ task.title }}</h3>
        {% if task.note %}
        <div class="card-text">{{ task.note|safe|urlize|linebreaks }}</div>
        {% endif %}
      </div>
    </div>

    <div class="card col-sm-4 p-0">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <button
            class="btn btn-sm btn-primary"
            id="EditTaskButton"
            type="button"
            data-toggle="collapse"
            data-target="#TaskEdit">
            Edit Task
          </button>

          <form method="post" action="{% url "todo:task_toggle_done" task.id %}" role="form" class="d-inline">
            {% csrf_token %}
            <div style="display:inline;">
              <button class="btn btn-info btn-sm" type="submit" name="toggle_done">
                {% if task.completed %} Mark Not Done {% else %} Mark Done {% endif %}
              </button>
            </div>
          </form>

          <form method="post" action="{% url "todo:delete_task" task.id %}" role="form" class="d-inline">
            {% csrf_token %}
            <div style="display:inline;">
              <button class="btn btn-danger btn-sm" type="submit" name="submit_delete">
                Delete
              </button>
            </div>
          </form>
        </li>
        <li class="list-group-item">
          <strong>Assigned to:</strong>
          {% if task.assigned_to %} {{ task.assigned_to.get_full_name }} {% else %} Anyone {% endif %}
        </li>
        <li class="list-group-item">
          <strong>Reported by:</strong> {{ task.created_by.get_full_name }}
        </li>
        <li class="list-group-item">
          <strong>Due date:</strong> {{ task.due_date }}
        </li>

        {% if task.completed %}
          <li class="list-group-item">
            <strong>Completed on:</strong> {{ task.completed_date}}
          </li>
        {% else %}
          <li class="list-group-item">
            <strong>Completed:</strong> {{ task.completed|yesno:"Yes,No" }}
          </li>
        {% endif %}

        <li class="list-group-item">
          <strong>In list:</strong>
          <a href="{% url 'todo:list_detail' task.task_list.id task.task_list.slug %}">
            {{ task.task_list }}
          </a>
        </li>
      </ul>
    </div>
  </div>

  <div id="TaskEdit" class="collapse">
    {# Task edit / new task form #}
    {% include 'todo/include/task_edit.html' %}
    {% if merge_form is not None %}
    <form action="" method="post">
      <div class="card border-danger">
      <div class="card-header">Merge task</div>
      <div class="card-body">
        <div class="">
          <p>Merging is a destructive operation. This task will not exist anymore, and comments will be moved to the target task.</p>
        {% csrf_token %}
        {% for field in merge_form.visible_fields %}
        <p>
          {{ field.errors }}
          {{ field }}
        </p>
        {% endfor %}
        <input class="d-inline btn btn-sm btn-outline-danger" type="submit" name="merge_task_into" value="Merge">
      </div>
      </div>
      </div>
    </form>
    {% endif %}
  </div>

{% if attachments_enabled %}
  <div class="card mt-4">
    <h5 class="card-header">
      Attachments
    </h5>

    <div class="card-body pb-0">
      {% if task.attachment_set.count %}
        <div class="table-responsive">
          <table class="table mb-3">
            <thead>
              <tr>
                <th>File</th>
                <th>Uploaded</th>
                <th>By</th>
                <th>Type</th>
                <th>Remove</th>
              </tr>
            </thead>
            <tbody>
              {% for attachment in task.attachment_set.all %}
                <tr>
                  <td><a href="{{ attachment.file_object.url }}">{{ attachment.filename }}</a></td>
                  <td>{{ attachment.timestamp }}</td>
                  <td>{{ attachment.added_by.get_full_name }}</td>
                  <td>{{ attachment.extension.lower }}</td>
                  <td>
                    <form action="{% url "todo:remove_attachment" attachment.id %}" method="POST">
                      {% csrf_token %}
                      <input type="submit" value="X" class="btn btn-danger btn-sm">
                    </form>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      {% endif %}

      <form method="POST" action="" enctype="multipart/form-data" style="width:50%;">
        {% csrf_token %}
        <div class="input-group mb-3">
          <div class="custom-file">
            <input type="file" class="custom-file-input" id="attachment_file_input" name="attachment_file_input" />
            <label class="custom-file-label" for="attachment_file_input">Choose file</label>
          </div>
          <div class="input-group-append">
            <button class="btn btn-primary">Upload</button>
          </div>
        </div>
      </form>

    </div>
  </div>
{% endif %}

  <div class="mt-3">
    <h5>Add comment</h5>
    <form action="" method="post">
      {% csrf_token %}
      <div class="form-group">
        <textarea class="form-control" name="comment-body" rows="3" required></textarea>
      </div>
      <input class="btn btn-sm btn-primary" type="submit" name="add_comment" value="Add Comment">
    </form>
  </div>

  <div class="task_comments mt-4">
    {% if comment_list %}
      <h5>Comments on this task</h5>
      {% for comment in comment_list %}
      <div class="mb-3 card">
        <div class="card-header">
          <div class="float-left">
            {% if comment.email_message_id %}
            <span class="badge badge-warning">email</span>
            {% endif %}
            {{ comment.author_text }}
          </div>
          <span class="float-right d-inline-block text-muted">
            {{ comment.date|date:"F d Y P" }}
          </span>
        </div>
        <div class="{{ comment_classes | join:" " }} card-body">
          {{ comment.body|safe|urlize|linebreaks }}
        </div>
      </div>
      {% endfor %}
    {% else %}
        <h5>No comments (yet).</h5>
    {% endif %}
  </div>
{% endblock %}

{% block extra_js %}
  {# Support file attachment uploader #}
  <script>
    $('#attachment_file_input').on('change',function(){
      // Get the file name and remove browser-added "fakepath."
      // Then replace the "Choose a file" label.
      var fileName = $(this).val().replace('C:\\fakepath\\', " ");
      $(this).next('.custom-file-label').html(fileName);
    })
  </script>
{% endblock extra_js %}